@host = https://auth.local.test
@route = /auth/register


### register
POST {{host}}{{route}} HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "Test!123"
}


### check
GET {{host}} HTTP/1.1