@host = https://auth.local.test
@route = /auth/login


### login with set cookie
POST {{host}}{{route}} HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "Test!123",
  "rememberMe": true
}


### login without set cookie
POST {{host}}{{route}} HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "Test!123",
  "rememberMe": false
}


### check
GET {{host}} HTTP/1.1
