@host = http://localhost:3000
@route = /register

### register
POST {{host}}{{route}} HTTP/1.1
content-type: application/json

{
  "email": "test6@test.com",
  "password": "Test!123"
}

### test

GET {{host}}{{route}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q2QHRlc3QuY29tIiwiaWF0IjoxNjI2Mzc5NjQ3LCJleHAiOjE2MjYzODAyNDcsImlzcyI6InVzZXIubG9jYWxob3N0LmlvIn0.KU7a7gWBoePdMu3VWjZ6uu0CltO5WRktx4OrASiYqfs
